spring:
  application:
    name: booking-system
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:bookingsystem
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: false
  sql:
    init:
      mode: ALWAYS